CurrentDirectory: /home/julienh/Desktop/COMP401/UniProtBot/Data/Drosophila
DataDir: /home/julienh/Desktop/COMP401/UniProtBot/Data
InputDir: /home/julienh/Desktop/COMP401/UniProtBot/Input
ArchiveDir: /home/julienh/Desktop/COMP401/UniProtBot/Archive
Analysis: /home/julienh/Desktop/COMP401/UniProtBot/Analysis
LastWorkedSpecies: Drosophila
