Annotated: /home/julienh/Desktop/COMP401/UniProtBot/Data/Drosophila/Annotated
Filtered: /home/julienh/Desktop/COMP401/UniProtBot/Data/Drosophila/Filtered
Proteome: /home/julienh/Desktop/COMP401/UniProtBot/Data/Drosophila/Proteome
Transcriptome: /home/julienh/Desktop/COMP401/UniProtBot/Data/Drosophila/Transcriptome
